[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myutils"
version = "1.6.26"
authors = [
  { name="Baijayanta Bhattacharyya", email="baijayantabhattacharyya2021@gmail.com" }
]
description = "Utility functions for MWA visibility simulation, TGE and PS estimation."
readme = "README.md"
requires-python = ">=3.6"

dependencies = [
    "numpy","scipy","astropy","healpy","numba",
]

[tool.setuptools.packages.find]
where = ["src"]
